### ISSUE TITLE
7.0系统，ListView列表，上拉更多后，下拉刷新出现bug

### ISSUE THREAD

**Issue by CK875430315** [iwgang/CountdownView#70]
java.lang.IndexOutOfBoundsException: Index: 14, Size: 10
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.dianzhi.xxxx.adapter.MyFabuListAdapter1New$4.onViewAttachedToWindow(MyFabuListAdapter1New.java)
	at android.view.View.dispatchAttachedToWindow(View.java:15412)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4493)
	at android.view.ViewGroup.addViewInLayout(ViewGroup.java:4430)
	at android.widget.ListView.setupChild(ListView.java:2023)
	at android.widget.ListView.makeAndAddView(ListView.java:1975)
	at android.widget.ListView.fillDown(ListView.java:704)
	at android.widget.ListView.fillGap(ListView.java:668)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5250)
	at android.widget.ListView.trackMotionScroll(ListView.java:1889)
	at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3595)
	at android.widget.AbsListView.onTouchMove(AbsListView.java:4022)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3830)
	at com.dianzhi.xianzhuan.view.XListView.onTouchEvent(XListView.java)
	at android.view.View.dispatchTouchEvent(View.java:9944)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3125)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
	at android.view.View.dispatchPointerEvent(View.java:10164)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4495)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4363)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4108)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6271)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6245)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6206)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6374)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6345)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6397)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
	at android.view.Choreographer.doFrame(Choreographer.java:615)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6114)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

    private void dealWithLifeCycle(final DebounceViewHolder holder, final int position) {
        holder.getCv_countdownView().addOnAttachStateChangeListener(new View.OnAttachStateChangeListener() {

            @Override
            public void onViewAttachedToWindow(View countdownView) {

//                    Log.d("MyViewHolder", String.format("mCvCountdownView %s is attachedToWindow", pos));

                holder.refreshTime(beans.get(position).expire*1000);
            }

            @Override
            public void onViewDetachedFromWindow(View countdownView) {
//                    int pos = position;
//                    Log.d("MyViewHolder", String.format("mCvCountdownView %s is detachedFromWindow", pos));

                holder.getCv_countdownView().stop();
            }
        });
    }

这个问题只出现在android7.0以上，项目里用的是listview，具体操作：列表上拉加载更多（2页数据）后在滑到顶部重新下拉刷新（1页数据）出现这个bug，holder.refreshTime(beans.get(position).expire*1000); 应该是这行出错

**Comment by CK875430315** [comment]
holder.refreshTime(beans.get(position).expire*1000);   holder.getCv_countdownView().stop();  干脆去掉这2个方法了，就好了

**Comment by iwgang** [comment]
这个是 LV 数据控制的问题，不是 CountdownView 引起的，注意下代码流程，CountdownView 在列表中仅推荐作为 View 显示，倒计时逻辑需要自己控制好
